# Generated by Django 6.1.1 on 2026-09-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consultant_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
