# Generated by Django 6.1.1 on 2026-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_consultant_approved_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consultant',
            field=models.BooleanField(default=False),
        ),
    ]
