# Generated by Django 6.1.1 on 2026-09-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'آپارتمان'), ('kolangi', 'کلنگی'), ('commercial', 'تجاری'), ('office', 'اداری')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('buyer', 'خریدار'), ('seller', 'فروشنده'), ('tenant', 'مستاجر'), ('landlord', 'موجر')], max_length=10, null=True),
        ),
    ]
