# Generated by Django 6.1.1 on 2026-09-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0003_district_buyapartmentrequest_delete_propertyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyapartmentrequest',
            old_name='has_elevator',
            new_name='has_elevaitor',
        ),
    ]
