# Generated by Django 6.1.1 on 2026-09-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0004_rename_has_elevator_buyapartmentrequest_has_elevaitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyapartmentrequest',
            old_name='has_elevaitor',
            new_name='has_elevator',
        ),
    ]
