# Generated by Django 6.1.1 on 2026-09-18 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0005_rename_has_elevaitor_buyapartmentrequest_has_elevator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyapartmentrequest',
            name='floor',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰+')]),
        ),
        migrations.CreateModel(
            name='SellApartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('seller', 'فروشنده'), ('buyer', 'خریدار'), ('tenant', 'مستاجر'), ('landlord', 'موجر')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('commercial', 'تجاری'), ('office', 'اداری'), ('kolangi', 'کلنگی')], max_length=20)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('exact_price', models.BigIntegerField(blank=True, null=True)),
                ('min_area', models.PositiveIntegerField(blank=True, null=True)),
                ('max_area', models.PositiveIntegerField(blank=True, null=True)),
                ('exact_area', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pictures', models.ImageField(upload_to='apartment_pictures/')),
                ('adress', models.CharField(max_length=150)),
                ('bedrooms', models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')])),
                ('units_per_floor', models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰')])),
                ('floor', models.SmallIntegerField(choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰+')])),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_storage', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filing_requests.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
