# Generated by Django 6.1.1 on 2026-09-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0006_alter_buyapartmentrequest_floor_sellapartmentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellapartmentrequest',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='sellapartmentrequest',
            name='pictures',
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='picture_1',
            field=models.ImageField(blank=True, upload_to='apartment_pictures/'),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='apartment_pictures/'),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='picture_3',
            field=models.ImageField(blank=True, upload_to='apartment_pictures/'),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='picture_4',
            field=models.ImageField(blank=True, upload_to='apartment_pictures/'),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='picture_5',
            field=models.ImageField(blank=True, upload_to='apartment_pictures/'),
        ),
    ]
