# Generated by Django 6.1.1 on 2026-09-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0008_rentapartmentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentapartmentrequest',
            old_name='is_convertable',
            new_name='is_convertible',
        ),
    ]
