# Generated by Django 6.1.1 on 2026-09-19 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0009_rename_is_convertable_rentapartmentrequest_is_convertible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartmentrequest',
            name='year_built',
            field=models.CharField(blank=True, choices=[('0-5', '۰ تا ۵ سال'), ('5-10', '۵ تا ۱۰ سال'), ('10-15', '۱۰ تا ۱۵ سال'), ('15-20', '۱۵ تا ۲۰ سال'), ('20+', 'بیش از ۲۰ سال')], max_length=40),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='year_built',
            field=models.CharField(blank=True, choices=[('0-5', '۰ تا ۵ سال'), ('5-10', '۵ تا ۱۰ سال'), ('10-15', '۱۰ تا ۱۵ سال'), ('15-20', '۱۵ تا ۲۰ سال'), ('20+', 'بیش از ۲۰ سال')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='floor',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰+')]),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='picture_1',
            field=models.ImageField(blank=True, upload_to='media/apartment/sell_apartment/'),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='media/apartment/sell_apartment/'),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='picture_3',
            field=models.ImageField(blank=True, upload_to='media/apartment/sell_apartment/'),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='picture_4',
            field=models.ImageField(blank=True, upload_to='media/apartment/sell_apartment/'),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='picture_5',
            field=models.ImageField(blank=True, upload_to='amedia/apartment/sell_apartment/'),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='units_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰')]),
        ),
        migrations.CreateModel(
            name='LeaseApartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('seller', 'فروشنده'), ('buyer', 'خریدار'), ('tenant', 'مستاجر'), ('landlord', 'موجر')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('commercial', 'تجاری'), ('office', 'اداری'), ('kolangi', 'کلنگی')], max_length=20)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('exact_price', models.BigIntegerField(blank=True, null=True)),
                ('min_area', models.PositiveIntegerField(blank=True, null=True)),
                ('max_area', models.PositiveIntegerField(blank=True, null=True)),
                ('exact_area', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture_1', models.ImageField(blank=True, upload_to='media/apartment/lease_apartment')),
                ('picture_2', models.ImageField(blank=True, upload_to='media/apartment/lease_apartment')),
                ('picture_3', models.ImageField(blank=True, upload_to='media/apartment/lease_apartment')),
                ('picture_4', models.ImageField(blank=True, upload_to='media/apartment/lease_apartment')),
                ('picture_5', models.ImageField(blank=True, upload_to='media/apartment/lease_apartment')),
                ('address', models.CharField(max_length=150)),
                ('bedrooms', models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')])),
                ('floor', models.SmallIntegerField(blank=True, choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰+')])),
                ('year_built', models.CharField(blank=True, choices=[('0-5', '۰ تا ۵ سال'), ('5-10', '۵ تا ۱۰ سال'), ('10-15', '۱۰ تا ۱۵ سال'), ('15-20', '۱۵ تا ۲۰ سال'), ('20+', 'بیش از ۲۰ سال')], max_length=40)),
                ('deposit', models.BigIntegerField()),
                ('monthly_rent', models.BigIntegerField()),
                ('is_convertible', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_storage', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filing_requests.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
