# Generated by Django 6.1.1 on 2026-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_requests', '0010_rentapartmentrequest_year_built_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyapartmentrequest',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='leaseapartmentrequest',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='leaseapartmentrequest',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='rentapartmentrequest',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='rentapartmentrequest',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='rentapartmentrequest',
            name='is_convertible',
        ),
        migrations.RemoveField(
            model_name='rentapartmentrequest',
            name='monthly_rent',
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='exact_deposit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='exact_monthly_rent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='max_deposit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='max_monthly_rent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='min_deposit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='min_monthly_rent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='occupancy_status',
            field=models.SmallIntegerField(choices=[(1, 'سکونت مالک'), (2, 'سکونت مستاجر'), (3, 'تخلیه')], default=1),
        ),
        migrations.AddField(
            model_name='leaseapartmentrequest',
            name='total_floors',
            field=models.SmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵')], default=1),
        ),
        migrations.AddField(
            model_name='rentapartmentrequest',
            name='max_deposit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapartmentrequest',
            name='max_monthly_rent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapartmentrequest',
            name='min_deposit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapartmentrequest',
            name='min_monthly_rent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='deed_status',
            field=models.SmallIntegerField(choices=[(1, 'تک برگ'), (2, 'دفترچه ای'), (3, 'قولنامه ای'), (4, 'اوقاف'), (5, 'تعاونی'), (6, 'در دست اقدام')], default=1),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='occupancy_status',
            field=models.SmallIntegerField(choices=[(1, 'سکونت مالک'), (2, 'سکونت مستاجر'), (3, 'تخلیه')], default=1),
        ),
        migrations.AddField(
            model_name='sellapartmentrequest',
            name='total_floors',
            field=models.SmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵')], default=1),
        ),
        migrations.AlterField(
            model_name='buyapartmentrequest',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')], default=1),
        ),
        migrations.AlterField(
            model_name='buyapartmentrequest',
            name='year_built',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'نوساز'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰'), (21, '۲۱'), (22, '۲۲'), (23, '۲۳'), (24, '۲۴'), (25, '۲۵'), (26, '۲۶'), (27, '۲۷'), (28, '۲۸'), (29, '۲۹'), (30, '۳۰+')], default=1),
        ),
        migrations.AlterField(
            model_name='leaseapartmentrequest',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')], default=1),
        ),
        migrations.AlterField(
            model_name='leaseapartmentrequest',
            name='floor',
            field=models.SmallIntegerField(choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵')], default=1),
        ),
        migrations.AlterField(
            model_name='leaseapartmentrequest',
            name='year_built',
            field=models.SmallIntegerField(choices=[(0, 'نوساز'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰'), (21, '۲۱'), (22, '۲۲'), (23, '۲۳'), (24, '۲۴'), (25, '۲۵'), (26, '۲۶'), (27, '۲۷'), (28, '۲۸'), (29, '۲۹'), (30, '۳۰+')], default=1),
        ),
        migrations.AlterField(
            model_name='rentapartmentrequest',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')], default=1),
        ),
        migrations.AlterField(
            model_name='rentapartmentrequest',
            name='year_built',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'نوساز'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰'), (21, '۲۱'), (22, '۲۲'), (23, '۲۳'), (24, '۲۴'), (25, '۲۵'), (26, '۲۶'), (27, '۲۷'), (28, '۲۸'), (29, '۲۹'), (30, '۳۰+')], default=1),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵+')], default=1),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='floor',
            field=models.SmallIntegerField(choices=[(-1, 'زیرزمین'), (0, 'همکف'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵')], default=1),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='units_per_floor',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰')], default=1),
        ),
        migrations.AlterField(
            model_name='sellapartmentrequest',
            name='year_built',
            field=models.SmallIntegerField(choices=[(0, 'نوساز'), (1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵'), (6, '۶'), (7, '۷'), (8, '۸'), (9, '۹'), (10, '۱۰'), (11, '۱۱'), (12, '۱۲'), (13, '۱۳'), (14, '۱۴'), (15, '۱۵'), (16, '۱۶'), (17, '۱۷'), (18, '۱۸'), (19, '۱۹'), (20, '۲۰'), (21, '۲۱'), (22, '۲۲'), (23, '۲۳'), (24, '۲۴'), (25, '۲۵'), (26, '۲۶'), (27, '۲۷'), (28, '۲۸'), (29, '۲۹'), (30, '۳۰+')], default=1),
        ),
    ]
